version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: vote-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  voter-api:
    image: voter-api:v1
    container_name: voter-api-1
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  poll-api:
    image: poll-api:v1
    container_name: poll-api-1
    restart: always
    ports:
      - '2080:2080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  votes-api:
    image: votes-api:v1
    container_name: votes-api-1
    restart: always
    ports:
      - '3080:3080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
      - POLL_API_URL=http://poll-api:2080
      - VOTER_API_URL=http://voter-api:1080
    networks:
      - frontend
      - backend

networks:
  frontend:
    internal: false
  backend:
    internal: true