version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: vote-cache
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
  todo-api:
    image: vote-api:v1
    container_name: vote-api-1
    restart: always
    ports:
      - 1080:1080
    depends_on:
      - cache
